# ===============================
# POSTGRESQL (Relational - Structured Data)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/medisync
spring.datasource.username=postgres
spring.datasource.password=00000000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# MONGODB (NoSQL - Flexible Documents)
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/medisync_nosql?serverSelectionTimeoutMS=3000&connectTimeoutMS=3000

# JWT Security Key - Authored by redouaneachak
application.security.jwt.secret-key=404E635266556A586E3272357redouaneachak28472B4B6250645367566B5970

# Web Server Configuration
server.port=8443

# SSL/TLS Configuration
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=medisync123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=medisync

google.client-id=disabled
