package com.medisync.model.enums;

public enum Permission {
    ACCESS_ADMIN_DASHBOARD,
    VIEW_FINANCIAL_REPORTS,
    VIEW_AUDIT_LOGS,
    MANAGE_USERS,
    MANAGE_CLINIC_PROFILE,
    MANAGE_ROOMS,
    MANAGE_MEDICAL_ACTS,
    MANAGE_PATIENTS,
    MANAGE_APPOINTMENTS,
    MANAGE_BILLING,
    MANAGE_DOCTOR_SCHEDULE,
    MANAGE_MEDICAL_RECORDS,
    VIEW_OWN_APPOINTMENTS,
    VIEW_OWN_MEDICAL_HISTORY,
    VIEW_OWN_BILLING,
    MANAGE_SELF_PROFILE,
    UPLOAD_MEDICAL_DOCUMENTS,
    SUBMIT_FEEDBACK,
    BOOK_APPOINTMENTS
}
